[[main]]
  identifier = "tags"
  name = "Tags"
  url = "tags"
  weight = 1

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 2

[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 3
